services:
  api:
    # build: ./app
    image: registry.innplay.site/sent-api:latest
    ports:
      - "32771:8000"
    depends_on:
      - alpine-llama
    networks:
      - api-network

  alpine-llama:
    image: samueltallet/alpine-llama-cpp-server
    # need to create new image that pulls newer llamacpp version...
    ports:
      - "50000:8080"
    environment:
      # - LLAMA_ARG_MODEL=/models/Llama-3.2-1B-Instruct-Q8_0.gguf
      # - LLAMA_ARG_ALIAS=Llama-3.2-1B-Instruct
      # - LLAMA_ARG_HF_REPO=bartowski/Llama-3.2-1B-Instruct-GGUF
      - LLAMA_ARG_HF_REPO=ggml-org/DeepSeek-R1-Distill-Qwen-1.5B-Q4_0-GGUF
      # - LLAMA_ARG_HF_FILE=Llama-3.2-1B-Instruct-Q8_0.gguf
      - LLAMA_ARG_HF_FILE=deepseek-r1-distill-qwen-1.5b-q4_0.gguf
      - LLAMA_ARG_ALIAS=DeepSeek-r1-Distill-Qwen-1.5B-Q4_0
      - LLAMA_API_KEY=sk-dummy
    volumes:
      - ./models:/models
    networks:
      - api-network

networks:
  api-network:

